# -*- coding: utf-8 -*-
"""Calculadora de partidas rankeadas

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WNgYzAtW5dTbCxxAAjAhoCzgKQfF7oZc
"""

def ranking():

  vit = int(input("Quantas vitórias você possui até agora?"))
  der = int(input("Quantas derrotas você possui até agora?"))

  rank = vit - der

  if rank < 10:
        nivel = "Ferro"
  elif 11 <= rank <= 20:
        nivel = "Bronze"
  elif 21 <= rank <= 50:
        nivel = "Prata"
  elif 51 <= rank <= 80:
        nivel = "Ouro"
  elif 81 <= rank <= 90:
        nivel = "Diamante"
  elif 91 <= rank <= 100:
        nivel = "Lendário"
  else:
        nivel = "Imortal"

  print("O herói tem saldo de", rank,"e está no nível",nivel,"!!!")


ranking()